"""initial schema: slips, games, cursors, sport graph

Revision ID: a86132cf9a85
Revises: 
Create Date: 2026-09-10 14:33:27.782879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86132cf9a85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slip_code'), ['code'], unique=True)

    op.create_table('slip_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slip_cursor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slip_cursor_country'), ['country'], unique=True)

    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=False),
    sa.Column('bettype', sa.String(length=255), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slip_id'], ['slip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('expiry', sa.Boolean(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slip_id'], ['slip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_slip_id'), ['slip_id'], unique=False)

    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamatt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('teamatt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamatt_id'], ['teamatt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('teamatt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamatt_id'], ['teamatt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('away_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('slip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['bet_id'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['slip_id'], ['slip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('teamatt')
    op.drop_table('league')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_slip_id'))

    op.drop_table('game')
    op.drop_table('bet')
    with op.batch_alter_table('slip_cursor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slip_cursor_country'))

    op.drop_table('slip_cursor')
    with op.batch_alter_table('slip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slip_code'))

    op.drop_table('slip')
    op.drop_table('country')
    # ### end Alembic commands ###
