"""empty message

Revision ID: b0dce6c7bee8
Revises: bcf69f3b12a3
Create Date: 2022-06-12 05:46:41.923633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dce6c7bee8'
down_revision = 'bcf69f3b12a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('outcome', sa.String(length=255), nullable=False))
    op.add_column('bet', sa.Column('bettype', sa.String(length=255), nullable=False))
    op.drop_column('bet', 'choice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('choice', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('bet', 'bettype')
    op.drop_column('bet', 'outcome')
    # ### end Alembic commands ###
