"""Model registry.

Importing this package registers every model with SQLAlchemy's metadata,
which Alembic and Flask-Migrate rely on for autogenerated migrations.
"""

from app.models.bet import Bet
from app.models.country import Country
from app.models.cursor import SlipCursor
from app.models.game import Game
from app.models.league import League
from app.models.match import Match
from app.models.player import Player
from app.models.slip import Slip
from app.models.team import Team
from app.models.team_att import TeamAtt

__all__ = [
    "Bet",
    "Country",
    "Game",
    "League",
    "Match",
    "Player",
    "Slip",
    "SlipCursor",
    "Team",
    "TeamAtt",
]
